spring.application.name=mangoa

# ==========================================
# CONFIGURACIÓN DE JWT
# ==========================================
# Clave secreta HMAC en Base64 de al menos 256 bits (32+ caracteres)
application.security.jwt.secret-key=${JWT_SECRET}
# Expiración en milisegundos (86400000 ms = 24 horas)
application.security.jwt.expiration=86400000

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ==========================================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
# ==========================================
# CONFIGURACIÓN DE OAUTH2 / GOOGLE LOGIN
# ==========================================
#spring.security.oauth2.client.registration.google.client-id=TU_CLIENT_ID_OBTENIDO.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=TU_CLIENT_SECRET_OBTENIDO
#spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:none}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:none}
spring.security.oauth2.client.registration.google.scope=email,profile